name: Semantic release
description: Creates release with semantic-release
author: rdeak
branding:
  icon: package
  color: blue
outputs:
  release_version:
    description: "The new releases' semantic version, i.e. `1.8.3`."
    value: ${{ steps.release.outputs.release-version }}
  release_major_version:
    description: "The new releases' major version number, i.e. `1`."
    value: ${{ steps.release.outputs.release-major-version }}
  release_tag:
    description: 'The version with v prefix.'
    value: ${{ steps.release.outputs.release-tag }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - run: npm ci
      shell: bash
    - run: node index.mjs
      shell: bash
      id: release
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ env.NPM_TOKEN }}


