name: Semantic release
description: Creates release with semantic-release
author: rdeak
branding:
  icon: package
  color: blue
outputs:
  new_release_created:
    description: "Flag if new release created (true/false)"
  release_version:
    description: "Latest released version eg. 1.0.1"
  release_major_version:
    description: "Latest major version eg. 1"
  release_tag:
    description: "Latest version tag eg. v1.0.1"
runs:
  using: "docker"
  image: "Dockerfile"
