name: Semantic release
description: Creates release with semantic-release
author: rdeak
branding:
  icon: package
  color: orange
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  NPM_TOKEN:
    description: "NPM token"
    required: false
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: latest
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Run semantic release
      run: node index.mjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
