name: Publish

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./
