name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: ./
        id: release-version
      - name: Tag major release
        if: ${{ steps.release-version.outputs.new_release_created }}
        shell: bash
        run: |
          git tag -a -m "v${{ steps.release-version.outputs.release_major_version }}" v${{ steps.release-version.outputs.release_major_version }}
          git push --follow-tags
      - name: Release summary
        shell: bash
        run: |
          echo "### Outputs" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| ----------- | ----- |" >> $GITHUB_STEP_SUMMARY
          echo "| new_release_created | ${{ steps.release-version.outputs.new_release_created }} |" >> $GITHUB_STEP_SUMMARY
          echo "| release_version | ${{ steps.release-version.outputs.release_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| release_major_version | ${{ steps.release-version.outputs.release_major_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| release_tag | ${{ steps.release-version.outputs.release_tag }} |" >> $GITHUB_STEP_SUMMARY
          echo  >> $GITHUB_STEP_SUMMARY
          echo "### Environment variables" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| ----------- | ----- |" >> $GITHUB_STEP_SUMMARY
          echo "| NEW_RELEASE_CREATED | ${{ env.NEW_RELEASE_CREATED }} |" >> $GITHUB_STEP_SUMMARY
          echo "| RELEASE_VERSION | ${{ env.RELEASE_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| RELEASE_MAJOR_VERSION | ${{ env.RELEASE_MAJOR_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| RELEASE_TAG | ${{ env.RELEASE_TAG }} |" >> $GITHUB_STEP_SUMMARY
