name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: ./
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release summary
        shell: bash
        run: |
          echo "### Outputs" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| ----------- | ----- |" >> $GITHUB_STEP_SUMMARY
          echo "| release-version | ${{ steps.release.outputs.release_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| release-major-version | ${{ steps.release.outputs.release_major_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| release-tag | ${{ steps.release.outputs.release_tag }} |" >> $GITHUB_STEP_SUMMARY
          echo  >> $GITHUB_STEP_SUMMARY
          echo "### Environment variables" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| ----------- | ----- |" >> $GITHUB_STEP_SUMMARY
          echo "| RELEASE_VERSION | ${{ env.RELEASE_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| RELEASE_MAJOR_VERSION | ${{ env.RELEASE_MAJOR_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| RELEASE_TAG | ${{ env.RELEASE_TAG }} |" >> $GITHUB_STEP_SUMMARY
